language: C
dist: artful

before_install:
  - sudo apt-get -qq update
  - sudo apt install -y bc kernel-package bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
  # Clone UberTc 4.8 toolchain. 
  #- git clone https://github.com/izaqKull/arm-eabi-4.9.git ~/arm-eabi-4.9/
  #- git clone https://github.com/nathanchance/gcc-prebuilts -b arm-gnu-7.x arm-gnu-7.x
  - git clone https://github.com/ikull/arm-linux-androideabi-4.9.git arm-linux-androideabi-4.9
  
  # make build script executable
  - chmod +x blaze.sh
  
install: true

script:
  - ./blaze.sh
  -

after_success:
- curl --upload-file outdir/iykonzBlaze/out_done/iykonzBlaze_woods*.zip https://transfer.sh/iykonzBlaze_woods_7.x_nouagt.zip
